config/routes.rb
Cookbook::Application.routes.draw do

  devise_for :users

  get "welcome/index"
  resources :categoria, :has_many => :receta 
  resources :categoria
  resources :receta

  resources :categoria do
  resources :receta

  end

  

  root :to => 'welcome#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :recetum
  
end

app/models/recetum.rb
class Recetum < ActiveRecord::Base
	belongs_to :categorium
	
	attr_accessible :descripcion, :ingredientes, :instrucciones, :titulo, :foto, :categorium_id
	
	has_attached_file :foto, :styles => { :small => "100x100>" }
	
	validates :titulo, :presence => true, :length => {:minimum => 3, :maximum => 50}
	validates :ingredientes, :presence => true
	validates :instrucciones, :presence => true
	validates :descripcion, :length => {:maximum => 150}
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  # GET /categoria
  # GET /categoria.json

before_filter :authenticate_user!
  def index
    @categoria = Categorium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
    @categorium = Categorium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categorium }
    end
  end

  # GET /categoria/new
  # GET /categoria/new.json
  def new
    @categorium = Categorium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categorium }
    end
  end

  # GET /categoria/1/edit
  def edit
    @categorium = Categorium.find(params[:id])
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(params[:categorium])

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render json: @categorium, status: :created, location: @categorium }
      else
        format.html { render action: "new" }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categoria/1
  # PUT /categoria/1.json
  def update
    @categorium = Categorium.find(params[:id])

    respond_to do |format|
      if @categorium.update_attributes(params[:categorium])
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium = Categorium.find(params[:id])
    @categorium.destroy

    respond_to do |format|
      format.html { redirect_to categoria_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/receta_controller.rb
class RecetaController < ApplicationController
  # GET /receta
  # GET /receta.json
before_filter :authenticate_user!
  def index
    @receta = Recetum.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receta }
    end
  end

  # GET /receta/1
  # GET /receta/1.json
  def show
      
    @recetum = Recetum.find(params[:id])

    if @recetum.nil?
      redirect_to :action => "index"
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recetum }
    end
  end

  # GET /receta/new
  # GET /receta/new.json
  def new
    @recetum = Recetum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recetum }
    end
  end
def upload
  uploaded_io = params[:person][:picture]
  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'w') do |file|
    file.write(uploaded_io.read)
  end
end

  # GET /receta/1/edit
  def edit
    @recetum = Recetum.find(params[:id])
   
  end

  # POST /receta
  # POST /receta.json
  def create
    @recetum = Recetum.new(params[:recetum])

    respond_to do |format|
      if @recetum.save
        format.html { redirect_to @recetum, notice: 'Su receta fue guardada exitosamente.' }
        format.json { render json: @recetum, status: :created, location: @recetum }
      else
        format.html { render action: "new" }
        format.json { render json: @recetum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receta/1
  # PUT /receta/1.json
  def update
    @recetum = Recetum.find(params[:id])

    respond_to do |format|
      if @recetum.update_attributes(params[:recetum])
        format.html { redirect_to @recetum, notice: 'Su receta fue modificada exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "editar" }
        format.json { render json: @recetum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receta/1
  # DELETE /receta/1.json
  def destroy
    @recetum = Recetum.find(params[:id])
    @recetum.destroy

    respond_to do |format|
      format.html { redirect_to receta_url }
      format.json { head :no_content }
    end
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
	def mark_required(object, attribute)
		"*" if object.class.validators_on(attribute).map(&:class).include? ActiveModel::Validations::PresenceValidator
	end
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/receta_helper.rb
module RecetaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categoria/_form.html.erb
  <%= form_for(@categorium) do |f| %>
    <% if @categorium.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@categorium.errors.count, "error") %> prohibited this categorium from being saved:
        </h2>

        <ul>
          <% @categorium.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div align= "center"; class="field">
      <%= f.label :nombre %><br />
      <%= f.text_field :nombre %>
    </div>
    <div align= "center"; class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/categoria/edit.html.erb
<div class="box">
	<h1>Editar categoría</h1>

	<%= render 'form' %>
	<div align= "center">
	<%= link_to 'Ver', @categorium %> |
	<%= link_to 'Atrás', categoria_path %>
</div>

app/views/categoria/index.html.erb
<div class="box">
  <h1>Categorías</h1>

  <table align= "center">
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
     </tr>

    <% @categoria.each do |categorium| %>
      <tr>
        <td><%= link_to categorium.nombre, categorium %></td>
        <td><%= link_to (image_tag ("/system/receta/fotos/lapiz.svg")), edit_categorium_path(categorium) %></td>
        <td><%= link_to (image_tag ("/system/receta/fotos/delt.svg")), categorium, method: :delete, data: { confirm: '¿Desea eliminar esta categoría?'} %></td>
      </tr>
    <% end %>
  </table>

  <br />
  <div align= "center">
  <%= link_to 'Nueva categoría', new_categorium_path %>
</div>

app/views/categoria/new.html.erb
<div class="box">

	<h1>Nueva categoría</h1>

	<%= render 'form' %>
	<div align= "center">
	<%= link_to 'Atrás', categoria_path %>
</div>

app/views/categoria/show.html.erb
<div class="box">
	<p id="notice"><%= notice %></p>

	<p>
	  <h1><%= @categorium.nombre %></h1>
	</p>
	<h3>Recetas:</h3>  
	<ul>  
	<% @categorium.recetum.each do |recetum| %>  
	    <li><%= link_to recetum.titulo, categorium_recetum_path(@categorium,recetum) %></li>  
	<% end %>  
	</ul>  
	  
	<br />  
	<%= link_to "Agregar receta", new_categorium_recetum_path(@categorium) %>  
	<hr style="margin-top:25px;"/>  
	  
	<%= link_to (image_tag ("/system/receta/fotos/lapiz.svg")), edit_categorium_path(@categorium) %> |  
	<%= link_to 'Categorías', categoria_path %>  

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Bon Profit</title>
	<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Cookie|Satisfy' rel='stylesheet' type='text/css'>
  	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
</head>
<body style="background: #B8D8D7;">
<div class="headerbox">

	<div class="logo">
		<%= link_to (image_tag ("/system/receta/fotos/logo.svg")), welcome_index_path %>
		<!--(image_tag ("/system/receta/fotos/logo.svg"))-->
	</div>
	
	<div id="user_nav">
		  <% if user_signed_in? %>
		    <div class="correousuario">
			    <%= current_user.email %>
			  	<div class="cerrarsesion">
			  		<%= link_to (image_tag ("/system/receta/fotos/cerrar.svg")), destroy_user_session_path, :method => :delete %>
			  	</div>
		    </div>
		  <% else %>
		  <div class="correousuario">
		    <%= link_to "regístrate", new_user_registration_path %> o <%= link_to "inicia sesión", new_user_session_path %>
		  </div>
		  <% end %>
	</div>


	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
	
<%= yield %>

</div>

</body>
</html>

app/views/receta/_form.html.erb
<%= simple_form_for @recetum, :html => { :multipart => true} do |f| %>
  <% if @recetum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recetum.errors.count, "error") %> prohibited this recetum from being saved:</h2>
      <ul>
      <% @recetum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  <% end %>


  <%= f.input :titulo %>
  <%= f.input :descripcion %>
  <%= f.input :ingredientes %>
  <%= f.input :instrucciones %>
  <%= f.input :foto %>

<%= f.collection_select :categorium_id, Categorium.all, :id, :nombre, :prompt => "Categoría "%>

<%= link_to "Categorías", categoria_path %>
<%= f.submit "Guardar" %>

<% end %>

app/views/receta/edit.html.erb
<h1>Modificar receta</h1>
	<%= render 'form' %>

	<%= link_to 'Ver', @recetum %> |
	<%= link_to 'Libro de recetas', receta_path %>

app/views/receta/index.html.erb
<div class="box">
<h1>Libro de recetas</h1>

	<% @receta.each do |recetum| %>
		<div class= "receta">
	  	
		  	<div class="imagenindex">
		  		<%= link_to (image_tag (recetum.foto.url(:small))), recetum %>
		  	</div>

		  	<div class="nombre">
		  			<%= link_to recetum.titulo, recetum %>
		  	</div></br>

		  	<div class= "indexdescripcion">	
		  		<%= recetum.descripcion %>
		  	
			  	<div class = "iconsindex">
			  		<%= link_to (image_tag ("/system/receta/fotos/lapiz.svg")), edit_recetum_path(recetum) %>
			  	</div>

			  	<div class = "iconsindex">
			  		<%= link_to (image_tag ("/system/receta/fotos/delt.svg")), recetum, method: :delete, data: { confirm: '¿Desea eliminar esta receta?' } %>
			  	</div>
		  	</div>
		</div>

	  	
    <% end %>

	<div class = "iconsindex">
	<%= link_to 'Nueva Receta', new_recetum_path %>
	</div>
	<div class = "iconsindex">
	<%= link_to 'Categoria', new_categorium_path %>
	</div>
</div>

app/views/receta/new.html.erb
	<h1>Nueva receta</h1>

	<%= render 'form' %>

	<%= link_to 'Libro de recetas', receta_path %>

app/views/receta/show.html.erb
<div class="box">
     
    <div class="imagen">
      <% if @recetum.foto? %>
        <%= link_to (image_tag (@recetum.foto.url(:small))), @recetum.foto.url %>
      <% end %>
    </div></br>

    <div class="titulo">
      <%= @recetum.titulo %>
    </div></br>

    <div class= "descripcion"> 
      <%= @recetum.descripcion %>
    </div></br>

    <div class= "ingredientes">
      <b>Ingredientes:</b></br></br>
      <%= @recetum.ingredientes %>
    </div>

    <div class="instrucciones">
      <b>Instrucciones:</b></br></br>
      <%= @recetum.instrucciones %>
    </div>

    <div class = "icons">
      <%= link_to (image_tag ("/system/receta/fotos/lapiz.svg")), edit_recetum_path(@recetum) %> 
    </div>
    <div class = "icons">
      <%= link_to (image_tag ("/system/receta/fotos/libro.svg")), receta_path %> 
    </div>


    <!--
    <div class = "icons">
      <%= link_to 'Categoría', categoria_path(@receta) %>
        <!-- ¿? Para ver la categoría a la que pertenece la receta: 
          action=> 'index', controller => 'categorium'
          categorium_receta
          receta#index
          categoria/:categorium_id/receta -->
    
    </div>

</div>

app/views/welcome/index.html.erb
<html>

<head>
      <%= stylesheet_link_tag "bonprofitwelcome" %>
</head>

<body onload="init()">
	<div class= "logotipo">
            <%= link_to (image_tag ("/system/receta/fotos/logotipo.svg")), welcome_index_path %>
      </div>

	<h1> bon profit </h1>

	<h2> Una aplicación que te permite guardar <br />
	y organizar tus recetas favoritas.</h2> 
      
      <h3><%= link_to 'recetas', receta_path %></h3>

</body>

</html>